-- 1. 실시간 가격 및 RSI 최신 상태 테이블 생성
CREATE TABLE IF NOT EXISTS public.current_status (
    symbol TEXT PRIMARY KEY,
    price DOUBLE PRECISION,
    rsi DOUBLE PRECISION,
    last_updated TEXT,
    rainbow_band TEXT,
    rainbow_color TEXT
);

-- 2. 매매 신호 로그 테이블 생성
CREATE TABLE IF NOT EXISTS public.signal_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT,
    timestamp TEXT,
    price DOUBLE PRECISION,
    rsi DOUBLE PRECISION,
    action TEXT,
    created_at TEXT
);

-- 3. 중복 알림 방지용 전송된 캔들 타임스탬프 기록 테이블 생성
CREATE TABLE IF NOT EXISTS public.sent_alerts (
    symbol TEXT,
    timestamp TEXT,
    PRIMARY KEY (symbol, timestamp)
);

-- RLS (Row Level Security) 설정 해제
-- REST API를 통해 인증 키(Anon Key)만으로 쉽게 읽고 쓸 수 있도록 RLS를 비활성화합니다.
ALTER TABLE public.current_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.signal_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sent_alerts DISABLE ROW LEVEL SECURITY;
